### ISSUE TITLE
I can't send Control Change message correctly.

### ISSUE THREAD

**Issue by linclip** [Microsoft/pxt-midi#1]
I send Control Change message with this library, I can't send it correctly.

I think that
"0xf" must be "0x7f" (max=127)
with file: "midi.ts"  Line: 232, 245, 259, 274

**Comment by Gadgetoid** [comment]
I think there are a few bugs like this in the code, see: https://www.midi.org/specifications-old/item/table-1-summary-of-midi-message

https://github.com/Microsoft/pxt-midi/blob/93ac2070833d169fe259dffd119a79992ae6a4ff/midi.ts#L243-L245

`0xf` masks to a 4-bit number, but the specification details both the key and value as 7-bit.

https://github.com/Microsoft/pxt-midi/blob/93ac2070833d169fe259dffd119a79992ae6a4ff/midi.ts#L285-L287

Again, as you mention, should be 7-bit (0-127)

Same with `channelMode`

**Comment by pelikhan** [comment]
Should be fixed now.

**Comment by linclip** [comment]
Please also fix the version described in pxt.json of "pxt-bluetooth-midi".

"midi": "github:Microsoft/pxt-midi#v2.0.3"
 to
"midi": "github:Microsoft/pxt-midi#v2.1.3"

**Comment by linclip** [comment]
I confirmed that pxt-bluetooth-midi has been fixed. Thank you.
