### ISSUE TITLE
erro 

### ISSUE THREAD

**Issue by tiaokisuki** [Microsoft/pxt-midi#10]
boa tarde a todos do grupo recentemente decidi fazer um projeto de arduino entao comprei um leonardo e uma mux 16 , e me enviaram o codigo pra mux ms quando carrego o codigo no monitor serial tudo normal as portas do analogicas do mux respondem normal porem no HAIERLESS da o seguindo erro .

+202.67 - Error: got unexpected data byte 0xd.

se necessario enviarei o codigo pro mux 

// Mapeamento dos pinos
#define SIG  A0   // pino analógico
#define S0   8
#define S1   9
#define S2   10
#define S3   11
// o pino EN do mux vai no GND

int mix[4]={S3,S2,S1,S0};

int valores_analogicos[16];

// Valores em binario 
byte ci[16][4]={
  {0,0,0,0},   // 0  em decimal
  {0,0,0,1},   // 1  em decimal
  {0,0,1,0},   // 2  em decimal
  {0,0,1,1},   // 3  em decimal
  {0,1,0,0},   // 4  em decimal
  {0,1,0,1},   // 5  em decimal
  {0,1,1,0},   // 6  em decimal
  {0,1,1,1},   // 7  em decimal
  {1,0,0,0},   // 8  em decimal
  {1,0,0,1},   // 9  em decimal
  {1,0,1,0},   // 10 em decimal
  {1,0,1,1},   // 11 em decimal  
  {1,1,0,0},   // 12 em decimal
  {1,1,0,1},   // 13 em decimal
  {1,1,1,0},   // 14 em decimal
  {1,1,1,1},   // 15 em decimal
};

void setup(){
Serial.begin(9600);

pinMode(S0,OUTPUT);
pinMode(S1,OUTPUT);
pinMode(S2,OUTPUT);
pinMode(S3,OUTPUT);

}

void loop(){
 
 // vai para a rotina de leitura do mux  
 multiplex();

   for (int x = 0; x <= 15; x++){
     Serial.print("Pino ");
     Serial.print(x);
     Serial.print(" = ");
     Serial.println(valores_analogicos[x]);
   }
 Serial.println("");

// Serial.print("Pino 15 = ");
// Serial.println(valores_analogicos[15]);  // de 0 a 15

// Esse delay pode ser removido    
delay(2000);

}// fim do loop

//Função de leitura dos valores
void multiplex(){

  for(int x=0; x <= 15; x++){
   for (int y = 0; y <= 3; y++){
      digitalWrite (mix[y], ci[x][y]);   
    }
    valores_analogicos[x] = analogRead(SIG);
  }
  
}// fim do multiplex

na imagem pode ver o referido erro 

![error](https://user-images.githubusercontent.com/104789572/166304236-aa94f415-46a6-496c-b6e5-4715c8a21ec8.JPG)

**Comment by pelikhan** [comment]
wrong project

**Comment by tiaokisuki** [comment]
pode identificar o erro amigo por favor o mesmo se refere a devida placa mux 16 que adquiri
