### ISSUE TITLE
serial unexpected data byte

### ISSUE THREAD

**Issue by machinehistories** [Microsoft/pxt-midi#3]
I am trying to use hairless midi serial bridge and I am getting an error: got unexpected data byte 0xa or some such incorrect byte. When I first start sending messages I get this error: +2648.05 - Warning: got a status byte when we were expecting 3 more data bytes, sending possibly incomplete MIDI message 0xff
Do you have any suggestions. I noticed it outputs the string "midi:" is this what it is complaining about. Also I believe MIDI::sendNoteOn(pitch, velocity, channel) is the correct order. Is the package sending channel, pitch, velocity. There is a description of a fix in this link [Control Change command "Unexpected data byte"](https://github.com/projectgus/hairless-midiserial/issues/16). thanks I look forward to getting it working over usb.

**Comment by Gadgetoid** [comment]
See #4 

To clarify, the actual messages sent look like:

```"midi:144,60,127                                                              \r\n"```

The "unexpected data byte" errors are Hairless attempting to parse this string data as MIDI, which will never work. Incidentally 0x20 is " ", 0xa is "\r" and 0xd "\n".

I've raised PR #5 with a proposed fix for this.
