### ISSUE TITLE
Midi signal via serial seems wrong

### ISSUE THREAD

**Issue by JonahPi** [Microsoft/pxt-midi#4]
I used the Midi package with a very simple program but was not able to get out any tone. Using a similar Python code worked perfectly fine. In both cases I transmit the Midi-code via Pin 0 and use the Midi via Serial command. When I compared the signals from the Phython code with the one from the PXT-code there was an obivious difference. (s.a. forum entry here: [link](https://forum.calliope.cc/t/midi-ausgabe-ueber-io-pins/406/7) )

**Comment by Gadgetoid** [comment]
I've just realised this when testing today- it's not actually sending MIDI over Serial at all, but is instead sending a string representation of it.

See: https://github.com/Microsoft/pxt-midi/blob/fb9de98860c6c5cd0a60844673f450f1bc55abbf/midi.ts#L80-L95

The practical upshot of this is that the "MIDI" is very human-readable, but unfortunately isn't readable by any off-the-shell Serial->MIDI bridge software I've come across.

The format is:

```midi:<command>,<arg>,<arg>                                                      \r\n```

(Not I've taken liberty with the amount of whitespace, but that is part of the output)

You could write your own client in Python that handles MIDI messages in this format and injects them directly into the system. It'd be relatively easy using `serial.readline`.

However I think this library needs a new block: "useRawSerial()"

This block would run the following code:

```typescript
function send(data: Buffer): void {
    serial.writeBuffer(data)
}
midi.setTransport(send);
```

This writes the raw - not human readable - MIDI data directly out to the serial port, and I can confirm this works with Hairless MIDI <-> Serial Bridge.

**Comment by JonahPi** [comment]
Using the new block "midi use raw serial" it works like a charm. Thanks a lot for your help!

**Comment by pelikhan** [comment]
Anyone up to write a project on how to use this?

**Comment by JonahPi** [comment]
![micromidiconnection](https://user-images.githubusercontent.com/6844732/40283811-cb598e68-5c84-11e8-83fb-8eac127f9430.PNG)
![microbitsamplecode](https://user-images.githubusercontent.com/6844732/40283815-d0789f92-5c84-11e8-83f7-3a36d9d7d573.PNG)

This setup allows to connect any kind of instrument with a midi-input. I tested it with an e-piano and [this little devices ](https://www.heise.de/make/meldung/NanoSynth-Breakout-Board-fuer-mehrstimmigen-Musikgenuss-3982004.html)which was described in the German Make magazine.

**Comment by CaptainCredible** [comment]
Nicely done! I originally wrote my own package for this that I haven't put
on gitgub yet. I have however run into trouble with hardware serial bytes
inexplicably going missing both on tx and rx. Have you stress tested this
yet?

**Comment by pelikhan** [comment]
@JonahPi , could we add this to the readme?

_____________________________

**Comment by JonahPi** [comment]
@pelikhan : Sure, 'would be cool to see more people using it.

@CaptainCredible : No long time tests run yet but I will work on a midi project soon, 'hope it works out.

**Comment by pelikhan** [comment]
@JonahPi can also help adding to the default list of projects.

_____________________________

**Comment by JonahPi** [comment]
In this case I think it should be a little bit extended to see the differences between polymorphic and single tones:
```
let Guitar: midi.MidiController = null
input.onButtonPressed(Button.A, () => {
    basic.showIcon(IconNames.EigthNote)
    Guitar.note(midi.frequencyToKey(262), music.beat(BeatFraction.Whole))
    basic.pause(100)
    Guitar.note(midi.frequencyToKey(330), music.beat(BeatFraction.Whole))
    basic.pause(200)
    Guitar.note(midi.frequencyToKey(440), music.beat(BeatFraction.Whole))
    basic.pause(300)
    basic.showIcon(IconNames.Yes)
})
input.onButtonPressed(Button.B, () => {
    basic.showIcon(IconNames.Heart)
    Guitar.noteOn(midi.frequencyToKey(262))
    Guitar.noteOn(midi.frequencyToKey(330))
    Guitar.noteOn(midi.frequencyToKey(440))
    basic.pause(800)
    Guitar.noteOff(midi.frequencyToKey(262))
    basic.pause(500)
    Guitar.noteOff(midi.frequencyToKey(330))
    basic.pause(500)
    Guitar.noteOff(midi.frequencyToKey(440))
    basic.showIcon(IconNames.Yes)
})
serial.redirect(
SerialPin.P0,
SerialPin.P1,
BaudRate.BaudRate31250
)
midi.useRawSerial()
basic.showIcon(IconNames.Yes)
Guitar = midi.channel(1)
Guitar.setInstrument(MidiInstrument.AcousticGuitarNylon)
```

>
