### ISSUE TITLE
Specifying Control Change parameters

### ISSUE THREAD

**Issue by linclip** [Microsoft/pxt-midi#8]
I can specify two parameters (CC # and value) in JavaSript Editor, but only 1 in Blocks Edtor.
The same, Polyphonic afer touch. 

Could you please correct  them?

https://github.com/Microsoft/pxt-midi/blob/3861e254d610c5c66728354afbf060bec6b892f0/midi.ts#L294
-->
//% blockId=midi_control_change block="%this|control change %fn| to %value"

https://github.com/Microsoft/pxt-midi/blob/3861e254d610c5c66728354afbf060bec6b892f0/midi.ts#L277
-->
//% blockId=midi_polyphonic_after_touch block="%this|polyphonic after touch %key| %pressure"

makecode.microbit.org Version: 0.14.54
Microsoft MakeCode Version： 0.19.16
C++ runtime Version： v2.1.0

**Comment by linclip** [comment]
Thank you very much.
Please also modify pxt.json of pxt-bluetooth-midi that references pxt-midi.

**Comment by pelikhan** [comment]
Updated.
